services:
  reservations:
    image: benasbudrys/roomr-reservations
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - ASPNETCORE_AuthUrl=http://auth:80
      - ASPNETCORE_ConnectionStrings_UsersDatabase="server=db;uid=root;pwd=example;database=users"
    ports:
      - 8000:80
    depends_on:
      - jaeger

  auth:
    image: benasbudrys/roomr-auth
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8001:16686

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
