services:
  reservations:
    image: roomrreservations
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - ASPNETCORE_AuthUrl=http://auth:80
    ports:
      - 8000:80
    depends_on:
      - jaeger

  auth:
    image: roomrreservations
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8001:16686
