services:
  reservations:
    image: benasbudrys/roomr-reservations
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - AuthUrl=http://auth:80
    ports:
      - 8000:80
    depends_on:
      - jaeger
      - auth

  auth:
    image: benasbudrys/roomr-auth
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - ConnectionStrings__UsersDatabase=server=db;uid=root;pwd=example;database=users
    depends_on:
      jaeger:
        condition: service_started
      db:
        condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 8001:16686

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
