name: Docker images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish-docker:
    strategy:
      matrix:
        project:
          [
            { path: Roomr.Reservations, name: roomr-reservations },
            { path: Roomr.Auth, name: roomr-auth },
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./${{ matrix.project.path }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.project.name }}:latest
